name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PRICE_FEED_BASE_URL: ${{ secrets.PRICE_FEED_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Build feeds service
        run: |
          cd feeds
          mvn clean verify

      - name: Build market service
        run: |
          cd market
          mvn clean verify

      - name: Build Docker images
        run: docker-compose build

      - name: Run services
        run: docker-compose up -d

      - name: Wait stage
        run: |
          sleep 15

      - name: Stop and clean up
        if: always()
        run: docker-compose down -v
